<a href="https://colab.research.google.com/github/eugeniohdez05/Laboratorio-de-aprendizaje-estadistico/blob/main/EX3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
ಥ_ಥ= files.upload()

Saving ret_next.csv to ret_next.csv

In [97]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [58]:
df= pd.read_csv("ret_next.csv")
df.head()

   y  ret_next  momentum        bm  ...    spread  leverage   liquidity       sector
0  1  0.041584  0.012829 -0.054778  ...  0.001586  0.499458  529.660760          NaN
1  0 -0.093096  0.479827 -0.922413  ...  0.005340  0.369037  380.973412       Energy
2  1  0.060016 -0.268646  0.007363  ...  0.017419  3.207282  697.893788   Healthcare
3  0  0.025898 -1.836360 -1.478547  ...  0.005470  0.257056  105.690037  Industrials
4  0 -0.046861 -0.432774 -0.487633  ...  0.001779  0.805322  192.022707   Technology

[5 rows x 12 columns]

In [59]:
df= df.dropna()
df.head()

   y  ret_next  momentum        bm  ...    spread  leverage   liquidity       sector
1  0 -0.093096  0.479827 -0.922413  ...  0.005340  0.369037  380.973412       Energy
2  1  0.060016 -0.268646  0.007363  ...  0.017419  3.207282  697.893788   Healthcare
3  0  0.025898 -1.836360 -1.478547  ...  0.005470  0.257056  105.690037  Industrials
4  0 -0.046861 -0.432774 -0.487633  ...  0.001779  0.805322  192.022707   Technology
5  1  0.054820  0.793818 -1.436254  ...  0.007039  0.240020  359.244397   Technology

[5 rows x 12 columns]

In [60]:
df= df.drop(["ret_next"], axis= 1)

In [61]:
log_reg= LogisticRegression()

In [62]:
y= df["y"]

In [63]:
num_transformer = StandardScaler()
cat_transformer = OneHotEncoder()
model = log_reg

In [64]:
X_cat= df["sector"]
X_cat= np.array(X_cat).reshape(-1,1)
X_num= df.drop(["y", "sector"], axis= 1)
X_num= np.array(X_num)

In [ ]:
#Algo hice mal con el one hot y se me fue el examen en eso ಥ_ಥ

In [92]:
X= X_num

In [93]:
log_reg.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [95]:
y_pred= log_reg.predict(X)

In [96]:
accuracy_score(y, y_pred)

0.6863496932515337

In [98]:
precision_score(y, y_pred)

0.6970128022759602